-- 코드를 입력하세요
SELECT DISTINCT USER_ID , PRODUCT_ID
FROM ONLINE_SALE o1
WHERE (SELECT COUNT(*) FROM ONLINE_SALE o2 WHERE o1.USER_ID = o2.USER_ID AND o1.PRODUCT_ID = o2.PRODUCT_ID) > 1
ORDER BY USER_ID, PRODUCT_ID DESC;