WITH RECURSIVE g AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    SELECT e.ID, e.PARENT_ID, GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA e JOIN g ON g.ID = e.PARENT_ID
)
SELECT COUNT(1) AS COUNT, GENERATION
FROM g LEFT JOIN ECOLI_DATA e ON g.ID = e.PARENT_ID
WHERE e.ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION