-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO NATURAL JOIN (SELECT FISH_TYPE, MAX(LENGTH) LENGTH
FROM FISH_INFO NATURAL JOIN FISH_NAME_INFO
GROUP BY FISH_TYPE) LONGEST NATURAL JOIN FISH_NAME_INFO
ORDER BY ID

